#!/bin/bash

GAME_ENV=(
# [ GENERAL SETTINGS ]
    DXVK_FRAME_RATE=224
    VKD3D_FRAME_RATE=224
# [ PROTON SETTINGS ]
    PROTON_USE_NVAPI=1
    PROTON_USE_NTSYNC=1
    PROTON_VKD3D_HEAP=1
    PROTON_DLSS_UPGRADE=1
    PROTON_ENABLE_NGX_UPDATER=1
# [ NVIDIA SETTINGS ]
    __GL_VRR_ALLOWED=1
    __GL_GSYNC_ALLOWED=1
    __GL_SYNC_TO_VBLANK=1
    DXVK_NVAPI_VKREFLEX=1
    GBM_BACKEND=nvidia-drm
    VKD3D_CONFIG=descriptor_heap
    DXVK_NVAPI_D3D12_NV_SHADER_EXTN=1
)

# [ GAMESCOPE FLAGS ]
GAMESCOPE_FLAGS=(
    --fullscreen
    --hdr-enabled
    --adaptive-sync
    --backend wayland
    --force-grab-cursor
)

# [ FLAGS ]
USE_HDR=0
USE_FG=0
USE_M=0
USE_NV=0
USE_CRT=0
USE_G=0
CAP_VALUE=""
SHIFT_CAP=0

for arg in "$@"; do
	case "$arg" in
		-hdr) USE_HDR=1 ;;
		-fg)  USE_FG=1 ;;
		-m)   USE_M=1 ;;
		-nv)  USE_NV=1 ;;
		-crt) USE_CRT=1 ;;
		-g)   USE_G=1 ;;
		-cap) SHIFT_CAP=1 ;;
		-all) USE_HDR=1; USE_FG=1; USE_M=1 ;;
		*)
			if [[ "$SHIFT_CAP" == "1" ]]; then CAP_VALUE="$arg"; SHIFT_CAP=0; fi ;;
	esac
done

# [ CLEAN ARGS ]
CLEAN_ARGS=()
SKIP_NEXT=0
for arg in "$@"; do
	if [[ "$SKIP_NEXT" == "1" ]]; then SKIP_NEXT=0; continue; fi
	case "$arg" in
		-hdr|-fg|-m|-nv|-all|-crt|-g) ;;
		-cap) SKIP_NEXT=1 ;;
		*) CLEAN_ARGS+=("$arg") ;;
	esac
done

# [ HDR ]
if [[ "$USE_HDR" == "1" ]]; then
    GAME_ENV+=( PROTON_ENABLE_WAYLAND=1 DXVK_HDR=1 )
fi

# [ FRAMEGEN | LSFG-VK ]
if [[ "$USE_FG" == "1" ]]; then
	GAME_ENV+=( ENABLE_LSFG=1 LSFG_PROCESS=FRAMEGEN LSFG_PERF_MODE=1 )
fi

# [ NVIDIA SMOOTH MOTION ]
if [[ "$USE_NV" == "1" ]]; then GAME_ENV+=( NVPRESENT_ENABLE_SMOOTH_MOTION=1 ); fi

# [ MANGOHUD ]
if [[ "$USE_M" == "1" ]]; then GAME_ENV+=( MANGOHUD=1 ); fi

# [ FRAME CAP ]
if [[ -n "$CAP_VALUE" ]]; then GAME_ENV+=( DXVK_FRAME_LIMIT="$CAP_VALUE" ); fi

# [ CRT SHADERS ]
if [[ "$USE_CRT" == "1" ]]; then
	STATE_FILE="$HOME/.config/hypr/Shaders/.Shader-ON"
	if [ ! -f "$STATE_FILE" ]; then
		cleanup() {
		hyprctl eval "ToggleCRT()"
		}
		trap cleanup EXIT
		hyprctl eval "ToggleCRT()"
	fi
fi

# [ GET CURRENT MONITOR MODE ]
read WIDTH HEIGHT REFRESH <<<$(hyprctl monitors | awk '
/Monitor/ {active=1}
/^[[:space:]]*[0-9]+x[0-9]+@[0-9.]+/ && active {
	split($1, a, "[@x]")
	print a[1], a[2], int(a[3])
	exit
}')

# [ ENABLE GAMESCOPE / HDR ]
if [[ "$USE_G" == "1" ]]; then
	LD_PRELOAD="" gamemoderun gamescope \
	-W "$WIDTH" -H "$HEIGHT" -r "$REFRESH" \
	"${GAMESCOPE_FLAGS[@]}" \
	-- env "${GAME_ENV[@]}" "${CLEAN_ARGS[@]}"
fi

# [ NORMAL EXECUTION ]
exec gamemoderun env "${GAME_ENV[@]}" "${CLEAN_ARGS[@]}"
