include ENCOM.conf
enable_audio_bell	no
font_size		14
shell			zsh

cursor_beam_thickness 	2
cursor_trail		3
cursor_shape		beam
cursor_shape_unfocused  beam	

confirm_os_window_close 0
resize_debounce_time 	0 0
hide_window_decorations yes
allow_remote_control 	yes
placement_strategy 	top-left
window_padding_width 	10 20 0 20
scrollback_indicator_opacity 0.0

tab_bar_min_tabs        1
tab_bar_edge 		bottom
active_tab_font_style	bold
inactive_tab_font_style	bold
tab_bar_align 		left
tab_separator             ""
tab_bar_style		separator
active_tab_title_template "  [ {title.upper()} ] "
tab_title_template        "  [ {index} | {title.upper()} ] "


# NERD FONT
 font_family      family='JetBrainsMono Nerd Font' style=Light
 bold_font        family='JetBrainsMono Nerd Font' style=ExtraBold
 italic_font      family='JetBrainsMono Nerd Font' style='Light Italic'
 bold_italic_font family='JetBrainsMono Nerd Font' style='ExtraBold Italic'

# TERMINAL FONT
# font_family      family="Courier Prime"
# bold_font        auto
# italic_font      auto
# bold_italic_font auto
