#!/usr/bin/env bash

STATE_FILE="$HOME/.config/waybar/Bar_Visible"
[ -f "$STATE_FILE" ] && rm "$STATE_FILE"

pkill -9 -x waybar
pkill -f WaybarAutoHide
pkill -9 swayosd-server
pkill -9 swaync
sleep 0.1
~/Scripts/ColorGen/GenerateColors
sleep 0.1
waybar >/dev/null 2>&1 &
swayosd-server >/dev/null 2>&1 &
