#!/usr/bin/env bash

STATE_FILE="$HOME/Scripts/.Screenshare-ON"
IDENTIFIERS="$HOME/.config/hypr/Config/Identifiers.conf"

    # [ SOURCE COLORS ]
eval "$(
    grep -E '^\$(PRIMARY|SECONDARY|BACKGROUND|ACCENT1|ACCENT2|ACCENT3)=' "$IDENTIFIERS" \
    | sed 's/^\$//'
)" 2>/dev/null

toggle_screenshare() {
if [ ! -f "$STATE_FILE" ]; then
    # [ ENABLE SCREENSHARING ]
    touch "$STATE_FILE"
else
    # [ DISABLE SCREENSHARING ]
    rm -f "$STATE_FILE"
fi
}

borders() {
if [ ! -f "$STATE_FILE" ]; then
    # [ RESTORE DEFAULT BORDERS ]
    hyprctl keyword 'windowrule[WORKSPACES]:decorate off'
    hyprctl keyword 'windowrule[SCREENSHARE]:enable true'
    hyprctl keyword decoration:shadow:color "rgba($PRIMARY""20)"
    hyprctl keyword general:col.active_border "rgb($PRIMARY)"
else
    # [ RESTORE SCREENSHARING BORDERS ]
    hyprctl keyword 'windowrule[WORKSPACES]:decorate on'
    hyprctl keyword 'windowrule[SCREENSHARE]:enable false'
    hyprctl keyword decoration:shadow:color "rgba($SECONDARY""15)"
    hyprctl keyword general:col.active_border "rgb($SECONDARY)"
fi
}

module() {
if [ ! -f "$STATE_FILE" ]; then
	ICON=""
	TOOLTIP="[ SESSION INCOGNITO ]"
else
	ICON=""
	TOOLTIP="[ SESSION VISIBLE ]"
fi

printf '{"text":"%s","tooltip":"%s"}\n' "$ICON" "$TOOLTIP"
}

case "${1,,}" in
    module) module ;;
    borders) borders;;
    *) 	toggle_screenshare
	borders;;
esac
