#!/usr/bin/env bash
STATE_FILE="$HOME/Scripts/.Screenshare-ON"

if [ ! -f "$STATE_FILE" ]; then
    ICON=""
    TOOLTIP="[ SESSION INCOGNITO ]"
else
    ICON=""
    TOOLTIP="[ SESSION EXPOSED ]"
fi

printf '{"text":"%s","tooltip":"%s"}\n' "$ICON" "$TOOLTIP"
