#!/usr/bin/env bash

STATE_FILE="$HOME/Scripts/.Screenshare-ON"
WINDOWRULES="$HOME/.config/hypr/Config/WindowRules.conf"
eval "$(sed 's/^\$//g' "$HOME/.config/hypr/Config/Identifiers.conf")" 2>/dev/null

toggle_screenshare() {
if [ -f "$STATE_FILE" ]; then
    # [ ENABLE SCREENSHARING ]
sed -i -e 's/decorate = on/decorate = off/' \
       -e 's/no_screen_share = off/no_screen_share = on/' "$WINDOWRULES"
    hyprctl reload
    hyprctl keyword decoration:shadow:color "rgba($PRIMARY""20)"
    hyprctl keyword general:col.active_border "rgb($PRIMARY)"
    rm -f "$STATE_FILE"
else
    # [ DISABLE SCREENSHARING ]
sed -i -e 's/decorate = off/decorate = on/' \
       -e 's/no_screen_share = on/no_screen_share = off/' "$WINDOWRULES"
    hyprctl reload
    hyprctl keyword decoration:shadow:color "rgba($SECONDARY""15)"
    hyprctl keyword general:col.active_border "rgb($SECONDARY)"
    touch "$STATE_FILE"
fi
}

module() {
if [ ! -f "$STATE_FILE" ]; then
	ICON=""
	TOOLTIP="[ SESSION INCOGNITO ]"
else
	ICON=""
	TOOLTIP="[ SESSION VISIBLE ]"
fi

printf '{"text":"%s","tooltip":"%s"}\n' "$ICON" "$TOOLTIP"
}

case "$1" in
    module) module ;;
    *) toggle_screenshare;;
esac
