#!/usr/bin/env bash

STATE_FILE=~/.config/waybar/Modules/.BluetoothDisabled

if [ -f $STATE_FILE ]; then
    bluetoothctl power on
    rm $STATE_FILE
else
    bluetoothctl power off
    touch $STATE_FILE
fi
