context.objects = [
    {   factory = adapter
        args = {
            factory.name     = support.null-audio-sink
            node.name        = "discord_sidechain"
            node.description = "Discord Sidechain"
            media.class      = Audio/Sink
            audio.position   = [ FL FR ]
        }
    }
]
