interpolation=no
video-sync=audio

glsl-shaders="/home/bashiie/.config/mpv/shaders/NVScaler.glsl"
glsl-shader="/home/bashiie/.config/mpv/shaders/FSRCNNX_x2_16-0-4-1.glsl"
glsl-shader="/home/bashiie/.config/mpv/shaders/SSimSuperRes.glsl"
glsl-shader="/home/bashiie/.config/mpv/shaders/CfL_Prediction.glsl"
glsl-shader="/home/bashiie/.config/mpv/shaders/KrigBilateral.glsl"
glsl-shader="/home/bashiie/.config/mpv/shaders/filmgrain.glsl"

profile-desc=p_hdr
profile-cond=(get("video-params/colormatrix") == "bt.2020-ncl") or (get("video-params/colormatrix") == "dolbyvision")
target-colorspace-hint=yes
target-peak=1000
hdr-contrast-recovery=0.30
hdr-peak-percentile=99.995
dither-depth=10
temporal-dither=yes
dither=ordered
inverse-tone-mapping=yes
dscale=hermite
profile=gpu-hq
vo=gpu-next
gpu-api=vulkan
hwdec=nvdec
dither-depth=auto
deband=yes
deband-iterations=4
deband-threshold=35
deband-range=24
deband-grain=4
#deband=no
scale=ewa_lanczossharp
cscale=ewa_lanczossharp
volume=50
volume-max=200
osc=no
cursor-autohide=3500         #synchronized with hidetimeout
osd-bar=no
