#!/usr/bin/env bash

# [ FILES ]
IDENTIFIERS="$HOME/.config/hypr/Config/Identifiers.lua"

# [ MAIN LOOP ]
while true; do
    inotifywait -e close_write "$IDENTIFIERS" >/dev/null 2>&1
hyprctl eval 'ReloadSystem()'
done
