#    ┳┓┳┏┓┏┓┓ ┏┓┓┏  ┏┓┏┓┏┳┓┏┳┓┳┳┓┏┓┏┓
#    ┃┃┃┗┓┃┃┃ ┣┫┗┫  ┗┓┣  ┃  ┃ ┃┃┃┃┓┗┓
#    ┻┛┻┗┛┣┛┗┛┛┗┗┛  ┗┛┗┛ ┻  ┻ ┻┛┗┗┛┗┛
monitorv2 {
	output =
	mode = preferred 
	position = 0x0
	scale = 1
	cm = auto
	supports_hdr = 1
	supports_wide_color = 1
	sdr_min_luminance = 0.01
	sdr_max_luminance = 400
	min_luminance = 0.005
	max_luminance = 600
	sdrsaturation = 1
	vrr = 3
}

#    ┏┓┏┓┳┳┳┓┏┓┏┓┳┓  ┏┓┏┓┳┓┏┓┳┏┓
#    ┗┓┃┃┃┃┣┫┃ ┣ ┃┃  ┃ ┃┃┃┃┣ ┃┃┓
#    ┗┛┗┛┗┛┛┗┗┛┗┛┻┛  ┗┛┗┛┛┗┻ ┻┗┛
source = Config/Identifiers.conf	# 	┏ IDENTIFIED VARIABLES
source = Config/Auto-Start.conf		# 	┣ AUTOMATIC STARTUPS
source = Config/Environment.conf	# 	┣ ENVIRONMENT VARIABLES
source = Config/Decorations.conf	# 	┣ DECORATIONS & ANIMATIONS
source = Config/Input.conf		# 	┣ INPUT & KEYBINDS
source = Config/Window-Rules.conf	# 	┣ WINDOW & LAYER RULES
source = Config/Miscellaneous.conf	# 	┣ EXPERIMENTAL SETTINGS
source = Config/Plugins.conf		# 	┣ PLUGIN CONFIGURATION
source = Config/Submappings.conf	# 	┗ SUBMAPPING INPUTS
