general {
	hide_cursor = true
	ignore_empty_input = true
	fail_timeout = 5000
}
background {
    	monitor =
    	color = rgba(000, 000, 000, 1)
}
label {
	font_size = 20
	position = -4%, 0%
	color = rgb(0, 255, 64)
	text = <b>INPUT SIGNAL:</b>
	font_family = JetBrainsMono Nerd Font
}
input-field {
    	monitor =
    	size = 10%, 6.5%
	position = 4%, 0%
    	placeholder_text =
    	fail_text = <b>ERROR: 404</b>
    	font_family = JetBrainsMono Nerd Font 
    	rounding = 0
    	dots_size = .2
    	dots_rounding = 0
    	dots_spacing = 0.75
	dots_center = false
    	fade_on_empty = false
	swap_font_color = true
    	outline_thickness = 0
    	fail_color = rgb(255, 0, 0)
    	inner_color = rgba(0, 0, 0, 0)
    	outer_color = rgba(0, 0, 0, 0)
    	font_color = rgb(235, 250, 250)
    	check_color = rgb(235, 250, 250)
	capslock_color = rgba(235, 250, 250, 1)

}
