general {
    	lock_cmd = pidof hyprlock || hyprlock
}

	# [ TURN OFF PANEL + BORDERS ]
listener {
    	timeout = 60
    	on-timeout = hyprctl keyword general:col.active_border "rgb(000000)" && hyprctl keyword decoration:shadow:color "rgba(000,000,000,0)"	
    	on-resume = ScreenShare Borders
}

	# [ REDUCE SCREEN BRIGHTNESS ]
listener {
	timeout = 120
    	on-timeout = hyprctl hyprsunset gamma 10
    	on-resume = hyprctl hyprsunset gamma 100
}

	# [ PAUSE DISCORD CLIENT ]
listener {
    	timeout = 180
    	on-timeout = loginctl lock-session && killall -STOP Discord 
 	on-resume = killall -CONT Discord
}

	# [ TURN OFF MONITOR ]
listener {
    	timeout = 210
    	on-timeout = hyprctl hyprsunset gamma 0
}
