general {
    	lock_cmd = pidof hyprlock || hyprlock
}

	# [ REMOVE/RESTORE BORDERS ]
listener {
    	timeout = 60
    	on-timeout = hyprctl keyword general:col.active_border "rgb(000000)"
	on-timeout = hyprctl keyword decoration:shadow:color "rgb(000000)"
    	on-resume = ScreenShare Borders
}

	# [ REDUCE/RESTORE SCREEN BRIGHTNESS ]
listener {
	timeout = 120
    	on-timeout = hyprctl hyprsunset gamma 10
    	on-resume = hyprctl hyprsunset gamma 100
}

	# [ PAUSE/RESUME DISCORD CLIENT ]
listener {
    	timeout = 180
    	on-timeout = loginctl lock-session
	on-timeout = killall -STOP Discord
 	on-resume = killall -CONT Discord
}

	# [ TURN OFF DISPLAY ]
listener {
    	timeout = 210
    	on-timeout = hyprctl hyprsunset gamma 0
}
