general {
	hide_cursor = true
	ignore_empty_input = true
	fail_timeout = 5000
}
background {
    	monitor =
	color = rgb(000000)
}

input-field {
    	monitor =
    	placeholder_text = <b>[ INPUT SIGNAL ]</b>
    	fail_text = <b>[ ERROR 404 ]</b>
    	font_family = JetBrainsMono Nerd Font 
    	rounding = 0
    	dots_size = .2
    	dots_rounding = 0
    	dots_spacing = 0.75
    	fade_on_empty = false
	swap_font_color = true
    	outline_thickness = 0
    	fail_color = rgb(255, 0, 0)
    	inner_color = rgb(000000)
    	outer_color = rgb(000000)
    	font_color = rgb(00FF40)
    	check_color = rgb(EBFAFA)
	capslock_color = rgb(EBFAFA)
}
