#!/usr/bin/env bash

STATE_FILE="$HOME/Scripts/.Screenshare-ON"
TOGGLE="ToggleScreenShare"

# Get Screenshare State
DID_ENABLE=false

# Enable Screenshare if Disabled
if [ ! -f "$STATE_FILE" ]; then "$TOGGLE" toggle; DID_ENABLE=true; fi

# Activate Hyprpicker
sleep 0.02; hyprpicker -a & HYPRSHOT_PID=$!

# Wait until Hyprpicker closes
while hyprctl clients | grep -qi hyprpicker; do sleep 0.01; done
wait "$HYPRSHOT_PID" 2>/dev/null

# Restore Screenshare State [if disabled]
if [ "$DID_ENABLE" = true ]; then "$TOGGLE" toggle; fi
