#!/usr/bin/env bash
# Toggle mute for the active window, including child processes

ACTIVE_PID=$(hyprctl activewindow -j | jq -r '.pid')
ACTIVE_TITLE=$(hyprctl activewindow -j | jq -r '.initialTitle')

if [ -n "$ACTIVE_PID" ]; then
        wpctl set-mute -p "$ACTIVE_PID" toggle
    notify-send "[ MUTE ACTIVE-WINDOW ]" "[  | $ACTIVE_TITLE ]"
else
    notify-send "[ MUTE FAILED! ]" "> NO CLIENT FOUND!"
fi
