#!/usr/bin/env bash

STATE_FILE="$HOME/Scripts/.Screenshare-ON"
WINDOWRULES="$HOME/.config/hypr/Config/WindowRules.conf"
source "$HOME/Scripts/ColorGen/Colors" 2>/dev/null

if [ -f "$STATE_FILE" ]; then
    # [ DISABLE SCREENSHARING ]
sed -i -e 's/decorate = off/decorate = on/' \
       -e 's/no_screen_share = on/no_screen_share = off/' "$WINDOWRULES"
    hyprctl reload
    hyprctl keyword decoration:shadow:color "rgba($TERTIARY""15)"
    hyprctl keyword general:col.active_border "rgb($SECONDARY) rgb($TERTIARY) 45deg"
fi
