#!/bin/bash

source "$HOME/Scripts/ColorGen/Colors"
STATE_FILE="$HOME/Scripts/.Screenshare-ON"
{ source "$HOME/Scripts/ColorGen/Colors"; } 2>/dev/null

sleep 1

if [ -f "$STATE_FILE" ]; then
	hyprctl keyword general:col.active_border "rgb($SECONDARY) rgb($TERTIARY) 45deg"
	hyprctl keyword decoration:shadow:color "rgba(${TERTIARY}15)"
else
	hyprctl keyword general:col.active_border "rgb($GRADIENT1) rgb($GRADIENT2) 45deg"
	hyprctl keyword decoration:shadow:color "rgba(${PRIMARY}20)"
fi
