#!/usr/bin/env bash

STATE_FILE="$HOME/Scripts/.Screenshare-ON"
WINDOWRULES="$HOME/.config/hypr/Config/Window-Rules.conf"

    # [ SOURCE COLORS ]
eval "$(
    grep -E '^\$(PRIMARY|SECONDARY|BACKGROUND|ACCENT1|ACCENT2|ACCENT3)=' "$HOME/.config/hypr/Config/Identifiers.conf" \
    | sed 's/^\$//'
)" 2>/dev/null

if [ -f "$STATE_FILE" ]; then
    # [ DISABLE SCREENSHARING ]
    hyprctl keyword 'windowrule[WORKSPACES]:decorate on'
    hyprctl keyword 'windowrule[SCREENSHARE]:enable false'
    hyprctl keyword decoration:shadow:color "rgba($SECONDARY""15)"
    hyprctl keyword general:col.active_border "rgb($SECONDARY)"
else
    # [ ENABLE SCREENSHARING ]
    hyprctl keyword 'windowrule[WORKSPACES]:decorate off'
    hyprctl keyword 'windowrule[SCREENSHARE]:enable true'
    hyprctl keyword decoration:shadow:color "rgba($PRIMARY""20)"
    hyprctl keyword general:col.active_border "rgb($PRIMARY)"
fi
