#!/usr/bin/env bash

STATE_FILE="$HOME/Scripts/.Screenshare-ON"
TOGGLE="ToggleScreenShare"

# Screenshare State
DID_ENABLE=false

# Obtain Screenshare State
if [ ! -f "$STATE_FILE" ]; then "$TOGGLE" toggle; DID_ENABLE=true; fi

# Execute Hyprshot [Screenshot PKG]
sleep 0.02; hyprshot -m window -m active -o ~/Pictures/Screenshots/ --silent & HYPRSHOT_PID=$!

# Wait for Hyprshot to Exit
while hyprctl clients | grep -qi screencopy; do sleep 0.01; done
wait "$HYPRSHOT_PID" 2>/dev/null

# Restore Screenshare State [if disabled]
if [ "$DID_ENABLE" = true ]; then "$TOGGLE" toggle; fi
