#!/usr/bin/env bash

STATE_FILE="$HOME/Scripts/.Screenshare-ON"
RULES_FILE="$HOME/.config/hypr/Config/WindowRules.conf"
source "$HOME/Scripts/ColorGen/Colors" 2>/dev/null

	# [ ENABLE SCREENSHARING ]
if [ -f "$STATE_FILE" ]; then
	hyprctl dispatch setprop class:vivaldi-stable no_screen_share on
	hyprctl dispatch setprop class:discord no_screen_share on
sed -i \
	-e 's/no_screen_share = \off/no_screen_share = on/' \
	-e 's/decorate = \on/decorate = off/' \
	"$RULES_FILE"
	hyprctl reload
	hyprctl keyword general:col.active_border "rgb($GRADIENT1) rgb($GRADIENT2) 45deg"
	hyprctl keyword decoration:shadow:color "rgba("$PRIMARY"20)"
	rm f "$STATE_FILE"
else
	# [ DISABLE SCREENSHARING ]
	hyprctl dispatch setprop class:vivaldi-stable no_screen_share off
	hyprctl dispatch setprop class:discord no_screen_share off
sed -i \
	-e 's/no_screen_share = \on/no_screen_share = off/' \
	-e 's/decorate = \off/decorate = on/' \
	"$RULES_FILE"
	hyprctl reload
	hyprctl keyword general:col.active_border "rgb($SECONDARY) rgb($TERTIARY) 45deg"
	hyprctl keyword decoration:shadow:color "rgba("$TERTIARY"15)"
	touch "$STATE_FILE"
fi
