#!/usr/bin/env bash

STATE_FILE="$HOME/Scripts/.Screenshare-ON"
WINDOWRULES="$HOME/.config/hypr/Config/WindowRules.conf"
source "$HOME/Scripts/ColorGen/Colors" 2>/dev/null

    # [ OBTAIN CLASSES | WINDOWRULES.CONF > NAME = SCREENSHARE ]
CLASSES=$(grep SCREENSHARE "$WINDOWRULES" -A2|grep match:class|sed 's/^.*=//;s/^[ \t]*//;s/[ \t]*$//')

if [ -f "$STATE_FILE" ]; then
    # [ ENABLE SCREENSHARING ]
sed -i -e 's/decorate = on/decorate = off/' \
       -e 's/no_screen_share = off/no_screen_share = on/' "$WINDOWRULES"
    hyprctl reload
    hyprctl keyword decoration:shadow:color "rgba($PRIMARY""20)"
    hyprctl keyword general:col.active_border "rgb($GRADIENT1) rgb($GRADIENT2) 45deg"
    rm -f "$STATE_FILE"
else
    # [ DISABLE SCREENSHARING ]
sed -i -e 's/decorate = off/decorate = on/' \
       -e 's/no_screen_share = on/no_screen_share = off/' "$WINDOWRULES"
    hyprctl reload
    hyprctl keyword decoration:shadow:color "rgba($TERTIARY""15)"
    hyprctl keyword general:col.active_border "rgb($SECONDARY) rgb($TERTIARY) 45deg"
    touch "$STATE_FILE"
fi
