#    ┳┓┳┏┓┏┓┓ ┏┓┓┏  ┏┓┏┓┏┳┓┏┳┓┳┳┓┏┓┏┓
#    ┃┃┃┗┓┃┃┃ ┣┫┗┫  ┗┓┣  ┃  ┃ ┃┃┃┃┓┗┓
#    ┻┛┻┗┛┣┛┗┛┛┗┗┛  ┗┛┗┛ ┻  ┻ ┻┛┗┗┛┗┛
monitorv2 {
	output =
	vrr = 3
	cm = auto
	scale = 1
	position = 0x0
	mode = preferred
	supports_hdr = 1
	min_luminance = 0
	max_luminance = 1000
	sdr_min_luminance = 0
	sdr_max_luminance = 400
	supports_wide_color = 1
}

#    ┏┓┏┓┳┳┳┓┏┓┏┓┳┓  ┏┓┏┓┳┓┏┓┳┏┓
#    ┗┓┃┃┃┃┣┫┃ ┣ ┃┃  ┃ ┃┃┃┃┣ ┃┃┓
#    ┗┛┗┛┗┛┛┗┗┛┗┛┻┛  ┗┛┗┛┛┗┻ ┻┗┛
source = Config/Identifiers.conf	# 	┏ IDENTIFIED VARIABLES
source = Config/Auto-Start.conf		# 	┣ AUTOMATIC STARTUPS
source = Config/Environment.conf	# 	┣ ENVIRONMENT VARIABLES
source = Config/Decorations.conf	# 	┣ DECORATIONS & ANIMATIONS
source = Config/Input.conf		# 	┣ INPUT & KEYBINDS
source = Config/Window-Rules.conf	# 	┣ WINDOW & LAYER RULES
source = Config/Miscellaneous.conf	# 	┗ EXPERIMENTAL SETTINGS
