#    ┏┓┳┳┏┳┓┏┓┳┳┓┏┓┏┳┓┳┏┓  ┏┓┏┳┓┏┓┳┓┏┳┓┳┳┏┓
#    ┣┫┃┃ ┃ ┃┃┃┃┃┣┫ ┃ ┃┃ ━━┗┓ ┃ ┣┫┣┫ ┃ ┃┃┃┃
#    ┛┗┗┛ ┻ ┗┛┛ ┗┛┗ ┻ ┻┗┛  ┗┛ ┻ ┛┗┛┗ ┻ ┗┛┣┛ 
# [ BACKGROUND STARTUP ]
exec-once = Waybar				# Waybar Script
exec-once = $Listener				# Color-Schemes
exec-once = $Sunshine				# Remote-Desktop
exec-once = solaar -w hide 			# Logitech Software
exec-once = vicinae server			# Application Launcher
exec-once = waypaper --random 			# Wallpaper Restoration
exec-once = swaync & swayosd-server &		# Notifications & OSD
exec-once = wl-clip-persist --clipboard regular	# Clipboard History

# [ HYPRLAND SPECIFIC ]
exec-once = $XDPH		# Hyprland Portals
exec-once = $Polkit		# Authentication Agent
exec-once = hypridle		# Auto-Lockscreen & Sleep
exec-once = hyprpm reload	# Reload Hyprland Config
exec-once = hyprsunset -i	# Blue-Light Disable & Gamma
exec-once = ScreenShare Borders	# Restore ScreenShare State

# [ GUI STARTUP ]
exec-once = $OBS 		# OBS
exec-once = steam		# Steam
exec-once = $Discord		# Discord
exec-once = $Browser		# Browser
exec-once = $EasyEffects	# Mic Equalizer

# [ TUI STARTUP ]
exec-once = [workspace 5 silent] $Terminal "kew"	# Music Player
exec-once = [workspace 5 silent] $Terminal "btop"	# System Monitor
exec-once = [workspace 5 silent] $Terminal "MC-Server"	# Minecraft Server
