#    ▄████▄ ██  ██ ██████ ▄████▄ ▄█████ ██████ ▄████▄ █████▄  ██████ 
#    ██▄▄██ ██  ██   ██   ██  ██ ▀▀▀▄▄▄   ██   ██▄▄██ ██▄▄██▄   ██   
#    ██  ██ ▀████▀   ██   ▀████▀ █████▀   ██   ██  ██ ██   ██   ██  

# BACKGROUND STARTUP
exec-once = vicinae server			# Application Launcher
exec-once = waybar & WaybarAutoHide &		# Waybar & Auto-Hide
exec-once = swaync & swayosd-server &		# Notifications & OSD
exec-once = wl-clip-persist --clipboard regular	# Clipboard History
exec-once = swww img ~/.config/hypr/Wallpapers/Test-Subjects.jpg 			# Restore Wallpaper

# HYPRLAND SPECIFIC
exec-once = $XDPH			# Faster Portals [1]
exec-once = $Polkit			# Authentication Agent
exec-once = hypridle			# Auto-Sleep Function
exec-once = hyprpm reload		# Update Hyprland Plugins
exec-once = RestoreBorders		# Restores Borders 
exec-once = hyprsunset -i		# Blue-Light Disable & Gamma

# GUI STARTUP
exec-once = $Browser		# Browser
