#    ██ ████▄  ██████ ███  ██ ██████ ██ ██████ ██ ██████ █████▄  ▄█████
#    ██ ██  ██ ██▄▄   ██ ▀▄██   ██   ██ ██▄▄   ██ ██▄▄   ██▄▄██▄ ▀▀▀▄▄▄
#    ██ ████▀  ██▄▄▄▄ ██   ██   ██   ██ ██     ██ ██▄▄▄▄ ██   ██ █████▀

# [ APPLICATIONS | MODIFIERS ]
$MOD = SUPER 		# 'SUPER' key
$Terminal = kitty	# Terminal
$Browser = vivaldi	# Browser
$FileManager = dolphin 	# File Manager
$Menu = vicinae toggle	# Application Launcher

# [ APPLICATIONS | FLAGS & VARIABLES ]
$Sunshine = PULSE_LATENCY_MSEC=0 sunshine
$OBS = com.obsproject.Studio --startreplaybuffer
$Discord = ELECTRON_OZONE_PLATFORM_HINT=x11 discord
$EasyEffects = QT_QPA_PLATFORMTHEME=gtk3 easyeffects

# [ GENERAL ENVIRONMENT ]
$Polkit = /usr/lib/mate-polkit/polkit-mate-authentication-agent-1
$Config = [float;size 1870 1000] $Terminal nvim ~/.config/hypr/hyprland.conf
$XDPH = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
$Listener = ~/Scripts/ColorGen/Listener

# [ COLORS ]
$BACKGROUND=000000
$PRIMARY=00FF40
$SECONDARY=EBFAFA
$ACCENT1=323449
$ACCENT2=212337
$ACCENT3=10111C
