#    ██▄  ▄██ ██ ▄█████ ▄█████ 
#    ██ ▀▀ ██ ██ ▀▀▀▄▄▄ ██     
#    ██    ██ ██ █████▀ ▀█████ 

misc {
    	vfr = true 
	#enable_anr_dialog = false	# [ APP 'NOT-RESPONDING' DIALOG ]
    	render_unfocused_fps = 240	# [ FPS FOR UNFOCUSED APPLICATIONS ]
    	force_default_wallpaper = 0	# [ NO FORCED WALLPAPERS ]
	background_color = 0x000000	# [ OLED-BLACK BACKGROUND]
    	disable_hyprland_logo = true	# [ DISABLE HYPRLAND SPLASH ]
}
render {
	#direct_scanout = 2		# [ LOW-LATENCY // NO-VRR ]
}
quirks {
	#prefer_hdr = 1			# [ HINT 'HDR' TO APPLICATIONS ]
}
xwayland {
    	force_zero_scaling = true	# [ xWAYLAND SCALING ] 
}
ecosystem {
    	no_donation_nag = true		# [ NO DONATION POP-UP ]
}
dwindle	{
    	preserve_split = true		# [ PRESERVE SPLITS ]
}
debug	{
	disable_logs = false		# [ SHOW DEBUG LOGS ]
	damage_tracking = 2		# [ 2 = DEFAULT | 0 = SHADERS ]
}

# [ HYPR-PLUGINS PERMISSIONS ]
permission = /usr/(bin|local/bin)/hyprpm, plugin, allow
