#    █████▄ ██     ██  ██  ▄████  ██ ███  ██ ▄█████ 
#    ██▄▄█▀ ██     ██  ██ ██  ▄▄▄ ██ ██ ▀▄██ ▀▀▀▄▄▄ 
#    ██     ██████ ▀████▀  ▀███▀  ██ ██   ██ █████▀ 

plugin {
    hyprexpo {
	gap_size = 20
        bg_col = rgb($BACKGROUND) 
        workspace_method = first 1
	}
}
